### ISSUE TITLE
Does this still work or did spotify kill it?

### ISSUE THREAD

**Issue by ihaddy** [akashrchandran/spotify-lyrics-api#46]
I thought this wouldn't work with free accounts because of spotify but i saw you pushed some changes only a few months ago, so do you mind if i ask the state of this project? Does it work with free accounts or just paid?

**Comment by c3kes** [comment]
Looks like Spotify bonked support for both Paid and Free accounts. Common spotify L [https://files.catbox.moe/epb0no.webp](url)

**Comment by c3kes** [comment]
> Looks like Spotify bonked support for both Paid and Free accounts. Common spotify L https://files.catbox.moe/epb0no.webp

Spotify just undid the update or something because it works now

**Comment by zhgh122** [comment]
@c3kes I always get {"error":true,"message":"lyrics for this track is not available on spotify!"} what did i do wrong

**Comment by akashrchandran** [comment]
Spotify changed the parameters for the get_access_token endpoint, so I updated it. Other than that, it should work now.

**Comment by zhgh122** [comment]
@akashrchandran  what i have to do?

**Comment by zhgh122** [comment]
@akashrchandran I tried your new version but still faced same error. Already set Cookie on environment variable

**Comment by iskiie** [comment]
I've updated, but it still doesn't work.

**Comment by akashrchandran** [comment]
Any error in the logs?

**Comment by c3kes** [comment]
> Any error in the logs?

Looks like spotify broke it again. You try to get a get_access_token https://[open.spotify.com/get_access_token?reason=transport&productType=Web_player](https://open.spotify.com/get_access_token?reason=transport&productType=Web_player) you get this message on spotify

{"error":{"code":400,"message":"Unauthorized request","extra":{"_notes":"Usage of this endpoint is not permitted under the Spotify Developer Terms and Developer Policy, and applicable law"}}}

**Comment by akashrchandran** [comment]
@ihaddy @c3kes @iskiie @zhgh122, Could you please try new commit? Now it's working locally for me, but on Vercel, it's not. Could you confirm? I don't have a premium account anymore, so if anyone has, try and let me know.

**Comment by zhgh122** [comment]
Ok I'll let y'all know after try on my premium acc.
@akashrchandran

**Comment by zhgh122** [comment]
@akashrchandran 
I have installed and ran your new commit using my Premium Account SP_DC 

Url : http://localhost:8080/?trackid=0u7Shj9zotYlZR1HTV04CX

{"error":true,"message":"lyrics for this track is not available on spotify!"}


Im not sure if this error come from the composer
I got these on composer install 

```
Composer could not detect the root package (akashrchandran/spotify-lyrics-api) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 5 installs, 0 updates, 0 removals
    Failed to download symfony/deprecation-contracts from dist: The zip extension and unzip/7z commands are both missing, skipping.
The php.ini used by your command-line PHP is: C:\php-8.4.5\php.ini
    Now trying to download from source
  - Syncing symfony/deprecation-contracts (v3.5.1) into cache
    Failed to download psr/clock from dist: The zip extension and unzip/7z commands are both missing, skipping.
The php.ini used by your command-line PHP is: C:\php-8.4.5\php.ini
    Now trying to download from source
  - Syncing psr/clock (1.0.0) into cache
    Failed to download paragonie/constant_time_encoding from dist: The zip extension and unzip/7z commands are both missing, skipping.
The php.ini used by your command-line PHP is: C:\php-8.4.5\php.ini
    Now trying to download from source
  - Syncing paragonie/constant_time_encoding (v3.0.0) into cache
    Failed to download symfony/polyfill-mbstring from dist: The zip extension and unzip/7z commands are both missing, skipping.
The php.ini used by your command-line PHP is: C:\php-8.4.5\php.ini
    Now trying to download from source
  - Syncing symfony/polyfill-mbstring (v1.31.0) into cache
    Failed to download spomky-labs/otphp from dist: The zip extension and unzip/7z commands are both missing, skipping.
The php.ini used by your command-line PHP is: C:\php-8.4.5\php.ini
    Now trying to download from s
```

**Comment by akashrchandran** [comment]
> Composer could not detect the root package (akashrchandran/spotify-lyrics-api) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version

Which composer version are you using?

**Comment by zhgh122** [comment]
@akashrchandran 

Can we contact on discord so it easier to communicate?

Composer version 2.8.6 2025-02-25 13:03:50
PHP version 8.4.5 (C:\php-8.4.5\php.exe)

**Comment by iskiie** [comment]
I use a premium account

![Image](https://github.com/user-attachments/assets/f36ec9df-8c25-41a3-8315-2e080481551c)

**Comment by akashrchandran** [comment]
> Can we contact on discord so it easier to communicate?

Yes sure

**Comment by iskiie** [comment]
> > I use a premium account
> > ![Image](https://github.com/user-attachments/assets/f36ec9df-8c25-41a3-8315-2e080481551c)
> 
> I have not yet published the package in the packagist. Try to clone locally and run

![Image](https://github.com/user-attachments/assets/27db2eb6-83ba-437e-8369-281683bfb778)

Strangely, I still can't use the script even though I have reinstalled it multiple times. I have also double-checked that the SP_DC has been updated.

**Comment by c3kes** [comment]
> [@ihaddy](https://github.com/ihaddy) [@c3kes](https://github.com/c3kes) [@iskiie](https://github.com/iskiie) [@zhgh122](https://github.com/zhgh122), Could you please try new commit? Now it's working locally for me, but on Vercel, it's not. Could you confirm? I don't have a premium account anymore, so if anyone has, try and let me know.

Hello! Thank you for your time! 

{"error":true,"message":"lyrics for this track is not available on spotify!"}

Using http://[localhost:8000/?trackid=5tVu9XCfGger7n38aPvfKg](http://localhost:8000/?trackid=5tVu9XCfGger7n38aPvfKg)

Premium Spotify account - not working for me locally

**Comment by sperrow** [comment]
Getting the same error with Spotify Premium

`{"error":true,"message":"lyrics for this track is not available on spotify!"}`

**Comment by MopigamesYT** [comment]
it was working for a little bit and it's happening again!!

{"error":true,"message":"lyrics for this track is not available on spotify!"}

**Comment by EnderFlop** [comment]
Mine is broken too. Strangely, it seems to work once every few days. At least, my status is still updating somehow, but it's happening too sparsely to notice when it happens.

**Comment by akashrchandran** [comment]
Check now, I have updated the codebase.
